services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
    command: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:5000 app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-prod.rule=Host(`eenkaartjeleggen.nl`)"
      - "traefik.http.routers.app-prod.entrypoints=websecure"
      - "traefik.http.routers.app-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-prod.loadbalancer.server.port=5000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
